# Generated by Django 4.1.1 on 2022-12-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_course_no_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='no_sem',
            field=models.IntegerField(default=6),
        ),
    ]
