# Generated by Django 4.1.1 on 2022-12-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_course_no_sem'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_id',
            field=models.IntegerField(default=0),
        ),
    ]
